import path from "node:path";
import { spawn } from "node:child_process";
import { createHash } from "node:crypto";

export const RUNTIME_DENY = Object.freeze({ sql: false, http: false, pgNet: false, collector: false, deploy: false, secrets: false, migrations: false, cron: false, production: false });
export const defaults = Object.freeze({ dryRun: true, autoMerge: false, concurrency: 1 });
export const allowedPaths = Object.freeze(["package.json", "scripts/agent-bridge/", "tests/agent-bridge/", ".github/ISSUE_TEMPLATE/agent-task.yml", ".github/PULL_REQUEST_TEMPLATE.md", ".github/labels.yml", ".github/workflows/agent-issue-contract.yml", ".github/workflows/agent-pr-contract.yml", "docs/AGENT_BRIDGE.md", "docs/BRIDGE_RUNBOOK.md", "docs/adr/0001-bounded-autonomous-agent-bridge.md", "docs/project-status.md", "docs/roadmap.md"]);
export function sanitize(value) { return String(value ?? "").replace(/(?:gh[pousr]_|github_pat_)[A-Za-z0-9_-]+/gi, "[redacted]").replace(/[A-Za-z]:\\[^\s"']+/g, "[private-path]"); }
export function normalizeRepoPath(value) { const raw = String(value ?? "").replaceAll("\\", "/"); if (!raw || raw.startsWith("/") || /^[A-Za-z]:\//.test(raw) || raw.split("/").includes("..")) return null; return raw.replace(/^\.\//, ""); }
export function validateChangedPaths(paths, permitted = allowedPaths) { const normalized = paths.map(normalizeRepoPath); const invalid = normalized.map((p, i) => p && permitted.some((a) => a.endsWith("/") ? p.startsWith(a) : p === a) ? null : paths[i]).filter(Boolean); return { valid: invalid.length === 0, invalid }; }
export function issueAllowedPaths(issue) { const body = String(issue?.body ?? ""); const section = body.match(/### Allowed paths\s*([\s\S]*?)(?=\n### |$)/i)?.[1] ?? ""; return [...section.matchAll(/`([^`]+)`/g)].map((m) => m[1]).filter(Boolean); }
const requiredContractSections = ["Goal", "Context", "In scope", "Out of scope", "Acceptance criteria", "Allowed paths", "Required checks", "Security constraints", "Dependencies", "Rollback", "Runtime permission matrix"];
export function substantiveSection(body, heading, level = "###") { const match = String(body ?? "").match(new RegExp(`(?:^|\\n)${level} ${heading}[^\\n]*\\n([\\s\\S]*?)(?=\\n${level} |$)`, "i")); return String(match?.[1] ?? "").replace(/<!--[\\s\\S]*?-->/g, "").replace(/_No response_/gi, "").trim(); }
export function parseIssueContract(issue) { const body = normalizeIssueBody(issue?.body); const sections = Object.fromEntries(requiredContractSections.map((h) => [h, substantiveSection(body, h)])); const allowedPaths = issueAllowedPaths({ body }); const requiredChecks = [...(sections["Required checks"].matchAll(/`([^`]+)`/g))].map((m) => m[1]); const valid = requiredContractSections.every((h) => sections[h].length > 0) && allowedPaths.length > 0 && requiredChecks.length > 0; return { valid, sections, allowedPaths, requiredChecks, runtimePermissions: sections["Runtime permission matrix"] }; }
export function normalizeIssueBody(body) { return String(body ?? "").replace(/\r\n/g, "\n").trim(); }
export function issueBodyDigest(body) { return createHash("sha256").update(normalizeIssueBody(body), "utf8").digest("hex"); }
export function validationEvidenceMatches(issue) { const evidence = issue?.validationEvidence; return Boolean(evidence?.author === "github-actions[bot]" && evidence?.version === "v1" && evidence?.digest === issueBodyDigest(issue?.body)); }
export function eligible(issue) { const labels = (issue?.labels ?? []).map((l) => l.name); return labels.includes("agent:ready") && !labels.some((l) => ["agent:running", "agent:review", "agent:blocked"].includes(l)) && validationEvidenceMatches(issue); }
export function parseConfig(args = [], env = process.env) { return { ...defaults, dryRun: args.includes("--dry-run") || env.BRIDGE_DRY_RUN !== "false" }; }
export function branchFor(issue) { return `agent/${issue.number}-${String(issue.title ?? "task").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 48) || "bridge-task"}`; }
export function codexCommand(platform = process.platform) { return platform === "win32" ? "codex.cmd" : "codex"; }
export function runChild(command, args, options = {}) { return new Promise((resolve, reject) => { const child = spawn(command, args, { ...options, shell: false, stdio: ["ignore", "pipe", "pipe"] }); let out = ""; let err = ""; child.stdout.on("data", (c) => { out += c; }); child.stderr.on("data", (c) => { err += c; }); child.on("error", reject); child.on("close", (code) => resolve({ code, output: sanitize(out), error: sanitize(err) })); }); }
export function promptFor(issue, context) { const contract = context.contract || parseIssueContract(issue); return JSON.stringify({ lifecycle: "agent:running", parentClaimed: true, issue: issue.number, contract: { goal: contract.sections.Goal, context: contract.sections.Context, inScope: contract.sections["In scope"], outOfScope: contract.sections["Out of scope"], acceptanceCriteria: contract.sections["Acceptance criteria"], allowedPaths: contract.allowedPaths, requiredChecks: contract.requiredChecks, securityConstraints: contract.sections["Security constraints"], dependencies: contract.sections.Dependencies, rollback: contract.sections.Rollback, runtimePermissionMatrix: contract.runtimePermissions }, branch: context.branch, worktree: context.worktree, childOwns: ["edit supplied worktree", "run approved checks", "return summary"], parentOwns: ["commit", "push", "pull request", "merge", "labels", "cleanup"], runtimePermissions: RUNTIME_DENY, issueBodyUntrusted: true }); }
export const SAFE_CHECKS = Object.freeze(["npm run test:bridge", "npm run check", "git diff --check"]);
export function validateRequiredChecks(commands) { const list = Array.isArray(commands) ? commands : []; return { valid: SAFE_CHECKS.every((c) => list.includes(c)) && list.every((c) => SAFE_CHECKS.includes(c)), commands: list }; }
export function prBody(issue, checks = SAFE_CHECKS) { const checked = SAFE_CHECKS.filter((c) => checks.includes(c)).map((c) => `- [x] \`${c}\``).join("\n"); return [`## Issue`, `\nCloses #${issue.number}`, `\n## Motivation`, `\nBounded single-task Bridge execution for one approved issue.`, `\n## Scope`, `\nOnly contract-allowed paths and one isolated task.`, `\n## Parent/child security boundary`, `\nParent owns Git/GitHub lifecycle; child edits only the supplied worktree.`, `\n## Runtime deny policy`, `\nSQL, HTTP, pg_net, collector, deploy, secrets, migrations, Cron, and production operations are denied.`, `\n## Tests`, `\n${checked}`, `\n## Manual post-merge configuration`, `\nHuman-managed labels, protection, and merge boundary.`, `\n## Explicit non-goals`, `\nNo batch, watch, process scanning, leases, auto-merge, installer, or runtime automation.`].join("\n"); }
export function dryRunPlan(issue) { return { outcome: "dry-run", issue: issue?.number ?? null, allowedPaths: issue ? ["sanitized issue contract"] : [], runtimeOperations: 0, mutations: 0 }; }
